// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gmirc.proto

package gMIRC;

/**
 * Protobuf type {@code gMIRC.UpdateString}
 */
public  final class UpdateString extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:gMIRC.UpdateString)
    UpdateStringOrBuilder {
  // Use UpdateString.newBuilder() to construct.
  private UpdateString(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private UpdateString() {
    newMessages_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private UpdateString(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            String s = input.readStringRequireUtf8();

            newMessages_ = s;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw new RuntimeException(e.setUnfinishedMessage(this));
    } catch (java.io.IOException e) {
      throw new RuntimeException(
          new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this));
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return gMIRC.gMIRC_proto.internal_static_gMIRC_UpdateString_descriptor;
  }

  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return gMIRC.gMIRC_proto.internal_static_gMIRC_UpdateString_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            gMIRC.UpdateString.class, gMIRC.UpdateString.Builder.class);
  }

  public static final int NEWMESSAGES_FIELD_NUMBER = 1;
  private volatile java.lang.Object newMessages_;
  /**
   * <code>optional string newMessages = 1;</code>
   */
  public java.lang.String getNewMessages() {
    java.lang.Object ref = newMessages_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      newMessages_ = s;
      return s;
    }
  }
  /**
   * <code>optional string newMessages = 1;</code>
   */
  public com.google.protobuf.ByteString
      getNewMessagesBytes() {
    java.lang.Object ref = newMessages_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      newMessages_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getNewMessagesBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, newMessages_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getNewMessagesBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, newMessages_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  public static gMIRC.UpdateString parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static gMIRC.UpdateString parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static gMIRC.UpdateString parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static gMIRC.UpdateString parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static gMIRC.UpdateString parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static gMIRC.UpdateString parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }
  public static gMIRC.UpdateString parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input);
  }
  public static gMIRC.UpdateString parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input, extensionRegistry);
  }
  public static gMIRC.UpdateString parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static gMIRC.UpdateString parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(gMIRC.UpdateString prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code gMIRC.UpdateString}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:gMIRC.UpdateString)
      gMIRC.UpdateStringOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return gMIRC.gMIRC_proto.internal_static_gMIRC_UpdateString_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return gMIRC.gMIRC_proto.internal_static_gMIRC_UpdateString_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              gMIRC.UpdateString.class, gMIRC.UpdateString.Builder.class);
    }

    // Construct using gMIRC.UpdateString.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      newMessages_ = "";

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return gMIRC.gMIRC_proto.internal_static_gMIRC_UpdateString_descriptor;
    }

    public gMIRC.UpdateString getDefaultInstanceForType() {
      return gMIRC.UpdateString.getDefaultInstance();
    }

    public gMIRC.UpdateString build() {
      gMIRC.UpdateString result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public gMIRC.UpdateString buildPartial() {
      gMIRC.UpdateString result = new gMIRC.UpdateString(this);
      result.newMessages_ = newMessages_;
      onBuilt();
      return result;
    }

    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof gMIRC.UpdateString) {
        return mergeFrom((gMIRC.UpdateString)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(gMIRC.UpdateString other) {
      if (other == gMIRC.UpdateString.getDefaultInstance()) return this;
      if (!other.getNewMessages().isEmpty()) {
        newMessages_ = other.newMessages_;
        onChanged();
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      gMIRC.UpdateString parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (gMIRC.UpdateString) e.getUnfinishedMessage();
        throw e;
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object newMessages_ = "";
    /**
     * <code>optional string newMessages = 1;</code>
     */
    public java.lang.String getNewMessages() {
      java.lang.Object ref = newMessages_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        newMessages_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string newMessages = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNewMessagesBytes() {
      java.lang.Object ref = newMessages_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        newMessages_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string newMessages = 1;</code>
     */
    public Builder setNewMessages(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      newMessages_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string newMessages = 1;</code>
     */
    public Builder clearNewMessages() {
      
      newMessages_ = getDefaultInstance().getNewMessages();
      onChanged();
      return this;
    }
    /**
     * <code>optional string newMessages = 1;</code>
     */
    public Builder setNewMessagesBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      newMessages_ = value;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:gMIRC.UpdateString)
  }

  // @@protoc_insertion_point(class_scope:gMIRC.UpdateString)
  private static final gMIRC.UpdateString DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new gMIRC.UpdateString();
  }

  public static gMIRC.UpdateString getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<UpdateString>
      PARSER = new com.google.protobuf.AbstractParser<UpdateString>() {
    public UpdateString parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      try {
        return new UpdateString(input, extensionRegistry);
      } catch (RuntimeException e) {
        if (e.getCause() instanceof
            com.google.protobuf.InvalidProtocolBufferException) {
          throw (com.google.protobuf.InvalidProtocolBufferException)
              e.getCause();
        }
        throw e;
      }
    }
  };

  public static com.google.protobuf.Parser<UpdateString> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<UpdateString> getParserForType() {
    return PARSER;
  }

  public gMIRC.UpdateString getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

