// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gmirc.proto

package gMIRC;

public interface UserMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:gMIRC.UserMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string username = 1;</code>
   */
  java.lang.String getUsername();
  /**
   * <code>optional string username = 1;</code>
   */
  com.google.protobuf.ByteString
      getUsernameBytes();

  /**
   * <code>optional string channelname = 2;</code>
   */
  java.lang.String getChannelname();
  /**
   * <code>optional string channelname = 2;</code>
   */
  com.google.protobuf.ByteString
      getChannelnameBytes();

  /**
   * <code>optional string msg = 3;</code>
   */
  java.lang.String getMsg();
  /**
   * <code>optional string msg = 3;</code>
   */
  com.google.protobuf.ByteString
      getMsgBytes();
}
