// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gmirc.proto

package gMIRC;

public interface UpdateStringOrBuilder extends
    // @@protoc_insertion_point(interface_extends:gMIRC.UpdateString)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string newMessages = 1;</code>
   */
  java.lang.String getNewMessages();
  /**
   * <code>optional string newMessages = 1;</code>
   */
  com.google.protobuf.ByteString
      getNewMessagesBytes();
}
