// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gmirc.proto

package gMIRC;

public interface UsernameOrBuilder extends
    // @@protoc_insertion_point(interface_extends:gMIRC.Username)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string username = 1;</code>
   */
  java.lang.String getUsername();
  /**
   * <code>optional string username = 1;</code>
   */
  com.google.protobuf.ByteString
      getUsernameBytes();
}
