// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gmirc.proto

package gMIRC;

public interface ResCodeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:gMIRC.ResCode)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int32 responseCode = 1;</code>
   */
  int getResponseCode();
}
