// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gmirc.proto

package gMIRC;

public final class gMIRC_proto {
  private gMIRC_proto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_gMIRC_Username_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_gMIRC_Username_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_gMIRC_UserChannel_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_gMIRC_UserChannel_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_gMIRC_UserMessage_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_gMIRC_UserMessage_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_gMIRC_ResCode_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_gMIRC_ResCode_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_gMIRC_UpdateString_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_gMIRC_UpdateString_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013gmirc.proto\022\005gMIRC\"\034\n\010Username\022\020\n\010user" +
      "name\030\001 \001(\t\"4\n\013UserChannel\022\020\n\010username\030\001 " +
      "\001(\t\022\023\n\013channelname\030\002 \001(\t\"A\n\013UserMessage\022" +
      "\020\n\010username\030\001 \001(\t\022\023\n\013channelname\030\002 \001(\t\022\013" +
      "\n\003msg\030\003 \001(\t\"\037\n\007ResCode\022\024\n\014responseCode\030\001" +
      " \001(\005\"#\n\014UpdateString\022\023\n\013newMessages\030\001 \001(" +
      "\t2\253\002\n\010grpcMIRC\022,\n\004Join\022\022.gMIRC.UserChann" +
      "el\032\016.gMIRC.ResCode\"\000\022,\n\007RegUser\022\017.gMIRC." +
      "Username\032\016.gMIRC.ResCode\"\000\022-\n\005Leave\022\022.gM" +
      "IRC.UserChannel\032\016.gMIRC.ResCode\"\000\022)\n\004Exi",
      "t\022\017.gMIRC.Username\032\016.gMIRC.ResCode\"\000\022/\n\007" +
      "Message\022\022.gMIRC.UserMessage\032\016.gMIRC.ResC" +
      "ode\"\000\0228\n\016RegularUpdates\022\017.gMIRC.Username" +
      "\032\023.gMIRC.UpdateString\"\000B\026\n\005gMIRCB\013gMIRC_" +
      "protoP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_gMIRC_Username_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_gMIRC_Username_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_gMIRC_Username_descriptor,
        new java.lang.String[] { "Username", });
    internal_static_gMIRC_UserChannel_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_gMIRC_UserChannel_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_gMIRC_UserChannel_descriptor,
        new java.lang.String[] { "Username", "Channelname", });
    internal_static_gMIRC_UserMessage_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_gMIRC_UserMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_gMIRC_UserMessage_descriptor,
        new java.lang.String[] { "Username", "Channelname", "Msg", });
    internal_static_gMIRC_ResCode_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_gMIRC_ResCode_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_gMIRC_ResCode_descriptor,
        new java.lang.String[] { "ResponseCode", });
    internal_static_gMIRC_UpdateString_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_gMIRC_UpdateString_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_gMIRC_UpdateString_descriptor,
        new java.lang.String[] { "NewMessages", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
